### ISSUE TITLE
"Exception: Failed to find regex match in html"

### ISSUE THREAD

**Issue by Mycah** [jtara1/imgur-downloader#21]
I was seeing this issue awhile back, but it "went away" but it appears to have returned.

```
$ python3.5 ~/imgur_downloader/imgur_downloader/imgurdownloader.py https://imgur.com/ADImt3B
Traceback (most recent call last):
  File "/home/mmattox/imgur_downloader/imgur_downloader/imgurdownloader.py", line 481, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mmattox/imgur_downloader/imgur_downloader/imgurdownloader.py", line 430, in main
    downloader = ImgurDownloader(url)
  File "/home/mmattox/imgur_downloader/imgur_downloader/imgurdownloader.py", line 156, in __init__
    self.json_imageIDs = list(self._init_image_ids_with_json(html=html))
  File "/home/mmattox/imgur_downloader/imgur_downloader/imgurdownloader.py", line 188, in _init_image_ids_with_json
    raise Exception("Failed to find regex match in html")
Exception: Failed to find regex match in html
```

**Comment by Mycah** [comment]
And now it works again.  I swear imgur is gaslighting me.

**Comment by crobo1337** [comment]
Having this error right now, looks like imgur just started requiring auth to access certain albums.

**Comment by jtara1** [comment]
@crobo1337 you mean to access private albums or just some public ones?

**Comment by crobo1337** [comment]
It looks like any posts tagged as NSFW require a login now.

https://blog.imgur.com/2019/10/14/discontinuing-support-for-nsfw-reddit-subsections/

Will likely require a re-work to grab an Auth token and pass that with the
request. Or just using the api directly.

**Comment by Mycah** [comment]
Looks like you can just embed an existing global api key to get it working.

https://github.com/mikf/gallery-dl/issues/446

**Comment by jtara1** [comment]
[gallery-dl ](https://github.com/mikf/gallery-dl/tree/master) supports downloading from the variety of links this project supports. I'm going to archive this repo.

Check for support for this there or report an issue there.
